# Source: olm/templates/0000_50_olm_15-packageserver.clusterserviceversion.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: packageserver
  namespace: openshift-operator-lifecycle-manager
  labels:
    olm.version: 0.19.0
    olm.clusteroperator.name: operator-lifecycle-manager-packageserver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  minKubeVersion: 1.11.0
  keywords: ['packagemanifests', 'olm', 'packages']
  maintainers:
    - name: Red Hat
      email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
    - name: Package Server
      url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - serviceAccountName: olm-operator-serviceaccount
          rules:
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
                - get
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - "operators.coreos.com"
              resources:
                - catalogsources
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - "packages.operators.coreos.com"
              resources:
                - packagemanifests
              verbs:
                - get
                - list
      deployments:
        - name: packageserver
          spec:
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxUnavailable: 1
                maxSurge: 1
            replicas: 2
            selector:
              matchLabels:
                app: packageserver
            template:
              metadata:
                labels:
                  app: packageserver
                annotations:
                  target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
                creationTimestamp: null
              spec:
                serviceAccountName: olm-operator-serviceaccount
                nodeSelector:
                  kubernetes.io/os: linux
                  node-role.kubernetes.io/master: ""
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoExecute
                    key: node.kubernetes.io/unreachable
                    operator: Exists
                    tolerationSeconds: 120
                  - effect: NoExecute
                    key: node.kubernetes.io/not-ready
                    operator: Exists
                    tolerationSeconds: 120
                containers:
                  - name: packageserver
                    command:
                      - /bin/package-server
                      - -v=4
                      - --secure-port
                      - "5443"
                      - --global-namespace
                      - openshift-marketplace
                    image: image-registry.openshift-image-registry.svc:5000/openshift/olm@sha256:5cabd6ee96bb542e3cf44f0c4b869d57d7e3fd2b55c88c4e0c106f5a82b796d9
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 5443
                        protocol: TCP
                    livenessProbe:
                      httpGet:
                        scheme: HTTPS
                        path: /healthz
                        port: 5443
                    readinessProbe:
                      httpGet:
                        scheme: HTTPS
                        path: /healthz
                        port: 5443
                    terminationMessagePolicy: FallbackToLogsOnError
                    resources:
                      requests:
                        cpu: 10m
                        memory: 50Mi
                    volumeMounts:
                      - name: tmpfs
                        mountPath: /tmp
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop: ["ALL"]
                volumes:
                  - name: tmpfs
                    emptyDir: {}
                priorityClassName: system-cluster-critical
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: app
                              operator: In
                              values:
                                - packageserver
                        topologyKey: "kubernetes.io/hostname"
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 65534
                  seccompProfile:
                    type: RuntimeDefault
  maturity: alpha
  version: 0.19.0
  apiservicedefinitions:
    owned:
      - group: packages.operators.coreos.com
        version: v1
        kind: PackageManifest
        name: packagemanifests
        displayName: PackageManifest
        description: A PackageManifest is a resource generated from existing CatalogSources and their ConfigMaps
        deploymentName: packageserver
        containerPort: 5443
  cleanup:
    enabled: false
  customresourcedefinitions: {}
